apiVersion: v1
kind: Service
metadata:
  name: service-management-service-svc
  namespace: service-management
spec:
  selector:
    app: service-management-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
